# Generated by Django 4.2 on 2023-07-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_tips', models.TextField(max_length=255, null=True)),
                ('result', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('play_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('away_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.footballteam')),
                ('home_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.footballteam')),
            ],
        ),
    ]
