# Generated by Django 4.2.3 on 2023-07-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_matchtips_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtips',
            name='is_free',
            field=models.IntegerField(default=0),
        ),
    ]
