# Generated by Django 4.2.3 on 2023-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_matchtips_play_date_alter_matchtips_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtips',
            name='play_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
