# Generated by Django 4.2.3 on 2023-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_alter_matchtips_play_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtips',
            name='play_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
